name: matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        node-version: [18, 20, 22, 24]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  build:
    strategy:
      matrix:
        node-version: [20, 22, 24]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Show info
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          node -v

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
